// University of La Laguna
// School of Engineering and Technology
// Bachelor's Degree in Computer Engineering
// Subject: Design and Analysis of Algorithms
// Course: 3rd
// Practice 6: Maximum Diversity Problem
// Author: Javier Acosta Portocarrero
// Date: 02/05/2026
// File maximum_diversity_solution_saver.cc: implementation file.
// Contains the implementation of the MaximumDiversitySolutionSaver class.

#include <fstream>
#include <iomanip>
#include <stdexcept>
#include <vector>

#include "maximum_diversity_solution_saver.h"

/**
 * @brief Saves a solution into the configured file.
 *
 * The method opens the file in append mode, so the new solution is added at the
 * end of the file without deleting previous solutions.
 *
 * @param solution Solution to save.
 * @param instance_name Name of the instance solved.
 * @param algorithm Algorithm used to obtain the solution.
 * @param execution Execution number.
 * @param cpu_time CPU time used to obtain the solution.
 * @param generated_nodes Number of nodes generated by the branch and bound
 * algorithm. A negative value means that this information is not available.
 *
 * @throw std::runtime_error If the output file cannot be opened.
 */
void MaximumDiversitySolutionSaver::Save(const MaximumDiversitySolution& solution,
                                         const std::string& instance_name,
                                         const std::string& algorithm,
                                         int execution,
                                         double cpu_time,
                                         int generated_nodes) const {
  std::ofstream output_file(file_path_, std::ios::app);
  if (!output_file) {
    throw std::runtime_error("Could not open solution output file: " + file_path_);
  }

  output_file << "============================================================\n";
  output_file << "Instance: " << instance_name << "\n";
  output_file << "Algorithm: " << algorithm << "\n";
  output_file << "Execution: " << execution << "\n";
  output_file << "n: " << solution.GetElementCount() << "\n";
  output_file << "K: " << solution.GetDimension() << "\n";
  output_file << "m: " << solution.GetSubsetSize() << "\n";

  output_file << std::fixed << std::setprecision(6);
  output_file << "CPU time: " << cpu_time << "\n";

  output_file << std::fixed << std::setprecision(6);
  output_file << "Obejective value: " << solution.GetObjectiveValue() << "\n";
  output_file << "Objective from scratch: " << solution.ComputeObjectiveFromScratch() << "\n";
  output_file << "Selected elements: " << solution.GetSelectedElementCount() << "\n";
  if (generated_nodes >= 0) {
    output_file << "Generated nodes: " << generated_nodes << "\n";
  }
  output_file << "Feasible: " << (solution.IsFeasible() ? "yes" : "no") << "\n\n";

  output_file << "Selected elements detail:\n";
  const std::vector<int>& elements = solution.GetElementsInSolution();
  for (int i = 0; i < static_cast<int>(elements.size()); ++i) {
    int element_id = elements[i];
    output_file << "  Element " << element_id << " | coordinates:";
    const std::vector<double>& coordinates = solution.GetInstance().GetElementCoordinates(element_id);
    for (int r = 0; r < static_cast<int>(coordinates.size()); ++r) {
      output_file << " " << coordinates[r];
    }
    output_file << " | contribution: " << solution.GetContributionOfElement(element_id) << "\n";
  }

  output_file << "\nPair distances:\n";
  for (int a = 0; a < static_cast<int>(elements.size()); ++a) {
    for (int b = a + 1; b < static_cast<int>(elements.size()); ++b) {
      output_file << "  Element " << elements[a]
                  << " - Element " << elements[b]
                  << " | distance: "
                  << solution.GetInstance().GetDistance(elements[a], elements[b])
                  << "\n";
    }
  }

  output_file << "\n";
}
